services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    restart: unless-stopped

  web:
    image: ${DOCKERHUB_USERNAME}/django-pallet-accounting_web:latest
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: ${DOCKERHUB_USERNAME}/django-pallet-accounting_nginx:latest
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume: 