# Generated by Django 5.2.4 on 2025-07-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер палеты')),
                ('pallets_from_the_date', models.DateField(verbose_name='Дата поступления')),
                ('pallet_pick_up_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('receipt_mark', models.BooleanField(default=False, verbose_name='Отметка о заказе')),
            ],
            options={
                'verbose_name': 'Палета',
                'verbose_name_plural': 'Палеты',
            },
        ),
        migrations.CreateModel(
            name='Poducts_in_palet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продукт в палете',
                'verbose_name_plural': 'Продукты в палете',
            },
        ),
        migrations.CreateModel(
            name='Poducts_in_palet_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('palet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_quantity', to='pallets.palet', verbose_name='Палета')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallets.poducts_in_palet', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в палете с количеством',
                'verbose_name_plural': 'Продукты в палете с количеством',
            },
        ),
    ]
