# Generated by Django 5.2.4

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

# SQL для создания функции и триггера.
# Он будет автоматически обновлять поле search_vector при каждом изменении product_name.
# 'russian' - словарь для русского языка.
trigger_sql = """
CREATE OR REPLACE FUNCTION update_poducts_in_palet_search_vector()
RETURNS TRIGGER AS $$
BEGIN
    NEW.search_vector := to_tsvector('russian', NEW.product_name);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER poducts_in_palet_search_vector_update
BEFORE INSERT OR UPDATE ON pallets_poducts_in_palet
FOR EACH ROW EXECUTE FUNCTION update_poducts_in_palet_search_vector();
"""

# SQL для удаления триггера и функции (при откате миграции).
reverse_trigger_sql = """
DROP TRIGGER IF EXISTS poducts_in_palet_search_vector_update ON pallets_poducts_in_palet;
DROP FUNCTION IF EXISTS update_poducts_in_palet_search_vector();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("pallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poducts_in_palet",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="poducts_in_palet",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="pallets_pod_search__e5e523_gin"
            ),
        ),
        # Этот шаг заполнит поле search_vector для уже существующих записей.
        migrations.RunSQL(
            "UPDATE pallets_poducts_in_palet SET search_vector = to_tsvector('russian', product_name);",
            "UPDATE pallets_poducts_in_palet SET search_vector = NULL;",
        ),
        # Этот шаг добавит триггер в базу данных.
        migrations.RunSQL(trigger_sql, reverse_trigger_sql),
    ]
