# Generated by Django 5.2.4 on 2026-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0002_add_search_vector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='poducts_in_palet',
            new_name='pallets_pod_search__7120f8_gin',
            old_name='pallets_pod_search__e5e523_gin',
        ),
        migrations.AlterField(
            model_name='palet',
            name='receipt_mark',
            field=models.BooleanField(verbose_name='Отметка о заказе'),
        ),
        migrations.AddIndex(
            model_name='palet',
            index=models.Index(fields=['receipt_mark', 'number'], name='pallets_pal_receipt_14802c_idx'),
        ),
        migrations.AddIndex(
            model_name='palet',
            index=models.Index(fields=['pallets_from_the_date'], name='pallets_pal_pallets_41ccfb_idx'),
        ),
        migrations.AddIndex(
            model_name='palet',
            index=models.Index(fields=['pallet_pick_up_date'], name='pallets_pal_pallet__d0470c_idx'),
        ),
        migrations.AddIndex(
            model_name='poducts_in_palet_quantity',
            index=models.Index(fields=['palet', 'product'], name='pallets_pod_palet_i_acf6a5_idx'),
        ),
    ]
